/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 car_reduced_started_blue_paint.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car_reduced_started_blue_paint.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.1}>
        <mesh geometry={nodes.frc12_4900_000_cfd_1.geometry} material={materials.Carbon} />
        <mesh geometry={nodes.frc12_4900_000_cfd_2.geometry} material={materials.Rubber} />
        <mesh geometry={nodes.frc12_4900_000_cfd_3.geometry} material={materials.Blue_paint} />
        <mesh geometry={nodes.frc12_4900_000_cfd_4.geometry} material={materials.Full_black} />
        <mesh geometry={nodes.frc12_4900_000_cfd_5.geometry} material={materials.Bright_metal} />
        <mesh geometry={nodes.frc12_4900_000_cfd_6.geometry} material={materials.White_paint} />
        <mesh geometry={nodes.frc12_4900_000_cfd_7.geometry} material={materials.Black_paint} />
      </group>
    </group>
  )
}

useGLTF.preload('/car_reduced_started_blue_paint.gltf')
