/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Podium.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Podium.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials.Podium_asphalt} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.podium_side} />
    </group>
  )
}

useGLTF.preload('/Podium.gltf')
